### ISSUE TITLE
Depth images exported as .exrs are empty.

### ISSUE THREAD

**Issue by raincrash** [pjessesco/RemoteCamera#3]
The exported depth images are blank. I could capture the RGB images, but the depth images are blank. I am using an iPhone 12 Pro. Is this expected?

**Comment by pjessesco** [comment]
Hi @raincrash, is the issue still reproduced with `client_example.py`?
Note that while `RCDCamera` sends RGB image as it, it sends depth **array**, not an image(which i didn't specify it in README...). Client must convert it to an image in some way, and `client_example.py` shows one example.

If it is not your case, could you show me your code snippet?

Thanks.

**Comment by raincrash** [comment]
Hi @pjessesco, Thank you for the quick reply. I have not modified the client example (except for the IP address) and pushed the main branch to an iPhone 12 Pro. And using the client from a different windows (WSL2) machine. Although, I get the images right, the depths (1.exr and 2.exr) return blank scenes.

**Comment by pjessesco** [comment]
Hi @raincrash, sorry for delay, because it was holiday in my country. I tested again without code changes(except filename), it works for my case. I run the script on windows, with iPad 4gen 12.9 inch.

![image](https://user-images.githubusercontent.com/11532321/107898806-10021100-6f80-11eb-84f9-6bb11c5327a6.png)

Is the blank images mean that there are only zero values?

**Comment by pjessesco** [comment]
Could you try [depth_png](https://github.com/pjessesco/RCDCamera/tree/depth_png) branch? It'll send depth image as PNG format.

**Comment by pjessesco** [comment]
Hi @raincrash, is there any update?
